### ISSUE TITLE
cant build this on qtcreator

### ISSUE THREAD

**Issue by haider-ali** [Esri/dynamic-situational-awareness-qt#277] opened 2018-06-12 07:30 UTC
i am getting /usr/bin/sh: -c: line 0: syntax error near unexpected token `(' error when build the DSA , any idea if  this is configuration issue?

**Comment by michael-tims** [comment] 2018-06-12 17:41
@haider-ali We're going to need more information to troubleshoot this with you.

Can you please provide the following:
- Which platform?  (Windows, Linux, etc...?)
  - Which OS and version on that platform?
- What is your Qt version?
- Does the project location on disk contain any spaces in the path?

**Comment by haider-ali** [comment] 2018-06-13 04:38
QT creator version is 4.5.1 on windows 64 bit
QT version is 5.10.1
targeting android(arm) only armeabi-v7a
No project location does not contain any space

**Comment by michael-tims** [comment] 2018-06-18 19:16
@haider-ali Thanks for that info.  Now that we have information that you are targeting Android armv7, can you please provide more information about the Android prerequisites that you've installed:

- What Android SDK version are you using to build the application?
- What Android NDK version?
- And finally, what Java JDK version?

**Comment by haider-ali** [comment] 2018-06-19 17:44
Android settings are OK. (SDK Version: 25.2.5, NDK Version: 17.0.4754217)
jdk1.8.0_112

**Comment by michael-tims** [comment] 2018-06-19 18:08
It may be a problem with the NDK.  Qt in general still recommends NDK 10e.  There are compatibility problems with the recent NDK versions and Qt, see http://doc.qt.io/qt-5/androidgs.html

Older versions of the NDK can be downloaded from https://developer.android.com/ndk/downloads/older_releases

**Comment by michael-tims** [comment] 2018-06-25 18:35
@haider-ali Did you clone the `arcgis-runtime-toolkit-qt` repo into your `dynamic-situational-awareness-qt` folder?

See https://github.com/Esri/dynamic-situational-awareness-qt#setup-the-arcgis-runtime-sdk-c-toolkit-as-a-build-dependency

It's stated as an optional step, but I believe it's required as the `master` branch of the `arcgis-runtime-toolkit-qt` repo contains changes needed by the DSA build.

**Comment by haider-ali** [comment] 2018-06-26 11:36
Yes i did that

1) git clone https://github.com/ArcGIS/dynamic-situational-awareness-qt.git
2) cd dynamic-situational-awareness-qt
 3) (skipped that) git clone https://github.com/Esri/arcgis-runtime-toolkit-qt.git 
instaed i ran the command git clone https://github.com/Esri/arcgis-runtime-toolkit-qt

4) open the project using QTCreator (4.5.1 Opensource)

5) configure the project for for_Android_armv7 

then this build error occurs

Assembler messages:
Fatal error: can't create ..\..\..\..\dynamic-situational-awareness-qt\arcgis-runtime-toolkit-qt\Plugin\CppApi\output\android\armv7\debug\obj\AbstractTool.obj: No such file or directory
make[1]: *** [..\..\..\..\dynamic-situational-awareness-qt\arcgis-runtime-toolkit-qt\Plugin\CppApi\output\android\armv7\debug\obj\AbstractTool.obj] Error 1
make[1]: Leaving directory `D:/Qt/DSA_APP/build-DSA-Android_for_armeabi_v7a_GCC_4_9_Qt_5_11_1_for_Android_armv7-Debug/arcgis-runtime-toolkit-qt/Plugin/CppApi'
make: *** [sub-D--Qt-DSA_APP-dynamic-situational-awareness-qt-arcgis-runtime-toolkit-qt-Plugin-CppApi-ArcGISRuntimeToolkit_StaticLib-pro-make_first-ordered] Error 2
16:34:07: The process "D:\Android\ndk\windows-x86_64\android-ndk-r10e\prebuilt\windows-x86_64\bin\make.exe" exited with code 2.
Error while building/deploying project DSA (kit: Android for armeabi-v7a (GCC 4.9, Qt 5.11.1 for Android armv7))
When executing step "Make"

**Comment by haider-ali** [comment] 2018-07-06 12:33
@michael-tims is it issue with my setup?

**Comment by michael-tims** [comment] 2018-07-13 18:21
@haider-ali Sorry for the delay, just getting back into the office after the Esri User Conference.  We were able to reproduce this problem (or a similar problem) locally with building for Android on Windows.  We hope to provide a solution/workaround or patch the projects with a proper fix over the next sprint.  I will keep you posted.

**Comment by michael-tims** [comment] 2018-07-19 19:15
@haider-ali I was able to build and run the Android DSA projects on Windows by shortening the path of the "Shadow build directory".

The default configured shadow build directory from the "Projects" tab in Qt Creator showed the directory as `C:\build-DSA-Android_for_armeabi_v7a_GCC_4_9_Qt_5_11_1_for_Android_armv7-Release`.  This can be far too long of a folder name for building Qt Android projects on Windows.  I simply renamed this build folder to `C:\build-DSA-Android` and then my build succeeded.

Can you please give this a try and let me know if it works/doesn't work for you?

**Comment by haider-ali** [comment] 2018-07-20 07:45
i was able to build the application by reducing the path of android build (D:\build-DSA-Android) and the project location(D:\dynamic-situational-awareness-qt)

**Comment by michael-tims** [comment] 2018-07-30 21:54
Closing this issue as "answered".  Please re-open if the proposed workaround stops working.

**Closed by michael-tims** 2018-07-30 21:54 UTC

**Comment by Stampit-CNC** [comment] 2019-07-16 06:11
hello everyone , i am facing a big issue while deploying android V8a on qt, i have recently installed qt 5.13 on windows but struggling with this issue -> clang++.exe: error: no such file or directory: 'c:\Utils\Android\android-ndk-r19c/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++.so.21'
make: *** [libMNSBLauncher.so] Error 1
11:32:36: The process "C:\Android\android-ndk-r19c\prebuilt\windows-x86_64\bin\make.exe" exited with code 2.
Error while building/deploying project mobilauncher (kit: Android for arm64-v8a (Clang Qt 5.13.0 for Android ARM64-v8a))
I have tried each solution available on google but yet unable to deploy, Please help me and save my time .

**Comment by JamesMBallard** [comment] 2019-07-16 14:38
@Stampit-CNC are you building the dynamic situational awareness app? Your error logs indicate you're building a different project.

Just off the top of my head looking at those errors, there are mixed path separators in `c:\Utils\Android\android-ndk-r19c/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++.so.21`, which could be part of the issue.

**Comment by Stampit-CNC** [comment] 2019-07-17 05:27
Hello Dear
Thanks a lot for your reply, you said there are mixed path you mean in environmental variable in qt ? because i have checked those paths seemed fine .


    On Tuesday, 16 July, 2019, 08:08:25 pm IST, James Ballard <notifications@github.com> wrote:  
 
 
@Stampit-CNC are you building the dynamic situational awareness app? Your error logs indicate you're building a different project.

Just off the top of my head looking at those errors, there are mixed path separators in c:\Utils\Android\android-ndk-r19c/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++.so.21, which could be part of the issue.

**Comment by Stampit-CNC** [comment] 2019-07-17 05:35
Sending you screenshot of my env. variable.
    On Tuesday, 16 July, 2019, 08:08:25 pm IST, James Ballard <notifications@github.com> wrote:  
 
 
@Stampit-CNC are you building the dynamic situational awareness app? Your error logs indicate you're building a different project.

Just off the top of my head looking at those errors, there are mixed path separators in c:\Utils\Android\android-ndk-r19c/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++.so.21, which could be part of the issue.

**Comment by khajra** [comment] 2019-07-20 00:16
@Stampit-CNC Your deployment does not look like the the dynamic situational awareness app. Your log says:
```
Error while building/deploying project mobilauncher (kit: Android for arm64-v8a (Clang Qt 5.13.0 for Android ARM64-v8a))
```
in which the project being deployed is `mobilauncher`.
