### ISSUE TITLE
App crash when removing a KML layer from the Overlays panel

### ISSUE THREAD

**Issue by dtedder** [Esri/dynamic-situational-awareness-qt#388] opened 2024-10-16 17:39 UTC
Tihs just happened once- the KML layer was the first one I added as an Overlay. I zoomed into it and then selected "Remove" from the layer options:

![Image](https://github.com/user-attachments/assets/d08aa479-7d5b-4938-9779-58a68b96c8e4)

and it crashed. 

I was then not able to reproduce the crash on any other layers I added to the Overlays list (including the same KML layer).

**Comment by dtedder** [comment] 2024-10-16 17:43
I have not been able to reproduce this. I am testing with a copy of the AOI.shp data that comes with the sample dataset that was converted to .kmz with ArcGIS Pro 3.3.1. Can you recall any steps you had done in the app around the time of the crash @kerryrobinson ? I attempted a few different combinations of the Zoom To and Remove options but never managed to reproduce the crash. I did not have any other data or feeds going during my testing. Can you share the data you were using in this screenshot, 'Tiger_Ro...'?

**Comment by kerryrobinson** [comment] 2024-10-31 00:30
I can't reproduce this so will close the issue, but will continue to test adding/removing overlays just to make sure.

**Closed by kerryrobinson** 2024-10-31 00:30 UTC
